# Generated by Django 6.0.4 on 2026-05-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
